# Generated by Django 3.2 on 2023-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nameb',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
