# Generated by Django 3.2 on 2023-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_nameb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
