# Generated by Django 3.2 on 2023-08-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='company',
        ),
    ]
