# Generated by Django 3.2 on 2023-09-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_user_address_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job_wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.wilaya'),
        ),
    ]
