# Generated by Django 3.2 on 2023-08-30 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_user_address_company'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_parent', to='user.manager'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
