# Generated by Django 3.2 on 2023-08-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_user_address_company'),
        ('user', '0002_auto_20230830_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
