# Generated by Django 3.2 on 2023-08-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_user_address_company'),
        ('user', '0004_auto_20230830_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.commune'),
        ),
        migrations.AlterField(
            model_name='address',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.wilaya'),
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
