# Generated by Django 3.2 on 2023-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230830_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
