from django.urls import path, include
from rest_framework.routers import DefaultRouter
from djoser.views import TokenCreateView, UserViewSet
from rest_framework_simplejwt.views import TokenRefreshView, TokenObtainPairView


from .views import (UserUpdateView,
                    CustomUserCreateView,
                    # CustomUserCreate,
                    AuthView,
                    CandidateList, 
                    CandidateDetail, 
                    SkillListCreateView, 
                    SkillRetrieveUpdateDestroyView,
                    EducationListCreateView,
                    EducationDetailView,
                    ExperienceList,
                    ExperienceDetail,
                    AddressListCreateView,
                    AddressRetrieveUpdateDestroyView,
                    ManagerListCreateView,
                    ManagerListSelectView,
                    ManagerRetrieveUpdateDestroyView,
                    InterviewList,
                    InterviewDetailList,
                    InterviewDetail,
                    QuestionListCreateAPIView,
                    QuestionRetrieveUpdateDestroyAPIView,
                    EventListCreateAPIView,
                    EventRetrieveUpdateDestroyAPIView,
                    CvListCreateView,
                    CvDetailView,
                    Managercurrent,
                    CandidateEventList,
                    EventDetailView,
                    InterviewDetailView,
                    CandidateCompanyListCreateAPIView,
                    CandidateViewDetail,
                    EventsDetailsView,
                    ManagerDetailsListCreateView,
                    InterviewCreateList,
                    ManagerPermissionCreateView,
                    ManagerPermissionListView,
                    create_update_manager_permission,
                    PermissionListAPIView,
                    HistoryListView,
                    TextProcessingView,
                    CurrentManager, 
                    PasswordTokenCheckAPI,
                    RequestPasswordResetEmail,
                    SetNewPasswordAPIView,
                    CandidateCVListView,
                    getAddress)
                    # CustomRegistrationView)
# from djoser.views import PasswordResetView, PasswordResetConfirmView

router = DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('api/auth/', include('djoser.urls')),
    path('api/auth/protected/', AuthView.as_view()),
    path('api/create-custom-user/', CustomUserCreateView.as_view(), name='create-custom-user'),
    path('api/password-reset/<uidb64>/<token>', PasswordTokenCheckAPI.as_view(), name='password-reset-confirm'),
    path('api/request-reset-email/', RequestPasswordResetEmail.as_view(), name='request-reset-email'),
    path('api/password-reset-complete/', SetNewPasswordAPIView.as_view(), name='password-reset-complete'),
    path('api/users/', UserViewSet.as_view({'post': 'create'}), name='user-create'),
    path('api/auth/token/', TokenCreateView.as_view(), name='token_create'),
    path('api/auth/token2/', TokenObtainPairView.as_view(), name='token_create'),
    path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token_create'),
    path('api/update-user/', UserUpdateView.as_view(), name='user_update'),
    path('candidates/', CandidateList.as_view(), name='candidate-list'),
    path('candidatesevents/', CandidateEventList.as_view(), name='candidate-list'),
    path('candidateCompanylist/', CandidateCompanyListCreateAPIView.as_view(), name='candidate-list-company'),
    path('candidates/<int:pk>/', CandidateDetail.as_view(), name='candidate-detail'),
    path('candidate/<int:pk>/', CandidateViewDetail.as_view(), name='candidate-view-detail'), # get basics data
    path('skills/', SkillListCreateView.as_view(), name='skill_list_create'),
    path('skills/<int:pk>/', SkillRetrieveUpdateDestroyView.as_view(), name='skill_retrieve_update_destroy'),
    path('education/', EducationListCreateView.as_view(), name='education_list_create'),
    path('education/<int:pk>/', EducationDetailView.as_view(), name='education_detail'),
    path('experiences/', ExperienceList.as_view()),
    path('experiences/<int:pk>/', ExperienceDetail.as_view()),
    path('addresses/', AddressListCreateView.as_view(), name='address-list-create'),
    #path('addresses/<int:pk>/', AddressRetrieveUpdateDestroyView.as_view(), name='address-retrieve-update-destroy'),
    path('addresses/<int:pk>/', getAddress, name='address-retrieve-update-destroy'),
    path('managersselect/', ManagerListSelectView.as_view(), name='manager_selectlist_create'),
    path('managers/', ManagerListCreateView.as_view(), name='manager_list_create'),
    path('managersDetails/<int:manager_id>/', ManagerDetailsListCreateView.as_view(), name='manager_list_create'),
    path('managers/<int:pk>/', ManagerRetrieveUpdateDestroyView.as_view(), name='manager_retrieve_update_destroy'),
    path('interviews-details/', InterviewDetailList.as_view(), name='interview-list'),
    path('interviews/', InterviewList.as_view(), name='interview-details-list'),
    path('interviewscreate/', InterviewCreateList.as_view(), name='interview-details-list'),
    path('interviews/<int:pk>/', InterviewDetail.as_view(), name='interview-detail'),
    path('interview-detail/<int:pk>/', InterviewDetailView.as_view(), name='interview-detail'),
    path('interviews/<int:interview_id>/questions/', QuestionListCreateAPIView.as_view(), name='question-list-create'),
    path('questions/<int:pk>/', QuestionRetrieveUpdateDestroyAPIView.as_view(), name='question-retrieve-update-destroy'),
    path('events/', EventListCreateAPIView.as_view(), name='event_list_create'),
    path('events/<int:pk>/', EventRetrieveUpdateDestroyAPIView.as_view(), name='event_retrieve_update_delete'),
    path('event-detail/<int:event_id>/', EventDetailView.as_view(), name='event-detail'),
    path('events-details/', EventsDetailsView.as_view(), name='events-details'),
    path('cvs/', CvListCreateView.as_view(), name='cv-list-create'),
    path('cvs/<int:pk>/', CvDetailView.as_view(), name='cv-detail'),
    path('api/get-cvs-for-candidates/<str:candidate_ids>/', CandidateCVListView.as_view(), name='candidate-cv-list'),
    path('managercurrent/<int:pk>/', Managercurrent.as_view(), name='manager-current'),
    path('currentmanager/<int:pk>/', CurrentManager.as_view(), name='current-manager'),
    path('permissions/', PermissionListAPIView.as_view(), name='permissions-list'),
    path('manager-permissions/', ManagerPermissionListView.as_view(), name='manager-permissions'),
    path('create-permissions/', create_update_manager_permission, name='create-permissions'),
    path('history/', HistoryListView.as_view(), name='history-list'),
    path('process-text/', TextProcessingView.as_view(), name='process-text'),
]